### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by LordEggNutz** [awitteck/sw-card-games#6]
Are there any instructions on how to actually utilize this mod?  I can see the rules of the games, but when it comes to how to deal the cards out to players and start playing, there is nothing.

**Comment by awitteck** [comment]
I have not implemented any special functionality into this mod. It only holds the decks as well as some rudimentary description of the rules.

You need to use the given playing card feature of foundry vtt, like create some players hand, discard piles,... and use them. 

Maybe there are some common mods which helps playing card in general. 

Card playing is a bit of a pain in foundry vtt.

**Comment by LordEggNutz** [comment]
Perfect, thanks for the explaination.
